### ISSUE TITLE
Mark as DEPRECATED / ARCHIVE or move the W3C CCG

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/lds-merkle-proof-2019#6]
@dsemenovsky @kimdhamilton 

As the only 2 contributors you are responsible for archiving this repo or moving it to the ccg... I suggest moving it to the CCG, it seems very valuable.

**Comment by OR13** [comment]
@AnthonyRonning Let us know your thoughts as well.

**Comment by OR13** [comment]
If no response is provided within 1 month, this repo should be archived.

**Comment by dsemenovsky** [comment]
Hi @OR13 I will get back to you shortly

**Comment by dsemenovsky** [comment]
How can we move it to CCG? I am relatively new to this, so would like some guidance

**Comment by OR13** [comment]
@dsemenovsky yes, however, since I am not an owner of this repo, I cannot do that for you. For context, please review: https://github.com/w3c-ccg/community/issues/105

@kimdhamilton can you help?

**Comment by AnthonyRonning** [comment]
I’m not sure of the best place for it but yes I agree wherever it needs to be, it would be great to move it there.

**Comment by OR13** [comment]
I moved this.
